### ISSUE TITLE
TO-DO list

### ISSUE THREAD

**Issue by Florian-DELRIEU** [Florian-DELRIEU/MyPack#23]
## `Myos.py`
- [x] Ajouter une fonction qui peut renommer les fichiers MSS.png de manière aléatoire

## `Math.py`

- [x] **`partial_mean`**: Fonction faisant la moyenne sur une partie des valeurs d'un array
  - **ex :** `func_name(array, indice, nb_valeur)` - fait la moyenne des `nb_valeur` dernière valeurs à partir de l'`indice`
  - [ ] Faire pareil pour le `min` et `max`
  - [ ] Need test

## `FFT.py`
- [ ] Pouvoir choisir l'unité des fréquence
  - **ex:** : `Hz` , `kHz`, `Periode par Jour`, `Periode par minute` etc ...
  - Ajouter un argument dans la fonction `freq` pour définir la durée (en seconde) `dt` du array `time`
  - `freq(..., interval_dt = 0.1)`
## General

- [ ] Reecrire les variable selon la convention

### Fonction print de progression
- [ ] Écrire une ligne en fonction de l'avancement d'un programme
  - En mesurant un variable par rapport à un nombre de loop
  - Choisir le tout les combien on veut le message ( manuellement si l'argument est une liste) 
- [ ] Afficher le temps de simulation
  - Soit le temps depuis le dernier log 
  - Soit temps cumulé
