### ISSUE TITLE
TODO LIST -- MyPack v3

### ISSUE THREAD

**Issue by Florian-DELRIEU** [Florian-DELRIEU/MyPack#31]
- [ ] Regrouper certains modules dans une meme dossier
- [ ] Renommer selon la convention de nommage
- [ ] Finir les TODO et FIXME
